server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:D:/35SCJ/databases/fiapcervejariabatch;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

file:
  path: D:/35SCJ/files/teste.txt
  input: classpath:pessoa.txt
